# AppVeyor CI build file

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

image: Visual Studio 2017

# version format
version: 2017.0.{build}

shallow_clone: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
- ps: .\Update-Version.ps1 -Version $env:APPVEYOR_BUILD_VERSION

build_script:
- ps: .\Build.ps1 -Configuration Release

after_build:
- ps: .\Pack.ps1 -Configuration Release

artifacts:
- path: artifacts\**\CertiPay.Taxes.State.*.nupkg

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - '**\bin\$(Configuration)\**\CertiPay.Taxes.State.Tests.dll'

#---------------------------------#
#       artifacts configuration   #
#---------------------------------#

deploy:
- provider: NuGet
  on: 
    branch: master
  api_key:
    secure: tj8axlUnLaJXMzsVHzNj6dT8VROvH1ChDSv9bKkQG4oNRB/6pI4oefW5WAhuIDIE